# Status: [planned]

from app.db.models.agent import Agent, AgentMessage, AgentRun, AgentSkill
from app.db.models.collaboration import (
    CourseUpdateDecision,
    CourseUpdateImpact,
    CourseUpdateSuggestion,
    ExternalSignal,
    Message,
    MessageDelivery,
)
from app.db.models.benchmark import BenchmarkCaseResult, BenchmarkDatasetVersion, BenchmarkRun
from app.db.models.education import (
    CourseEnrollment,
    CourseTeacherAssignment,
    GovernanceAuditEvent,
    StudentGroup,
    StudentGroupMember,
    TeachingClass,
    TeachingClassTeacher,
)
from app.db.models.fairness import (
    FairnessAlert,
    FairnessAppeal,
    FairnessConsent,
    FairnessGroupAssignment,
    FairnessMetricCell,
    FairnessMetricRun,
    FairnessPolicy,
    FairnessReview,
)
from app.db.models.identity import ProviderCredential, User, UserCapability, UserProfile
from app.db.models.governance import (
    CourseResourceGovernance,
    KpiDefinition,
    RoleDefinition,
    UserRoleGrant,
)
from app.db.models.security import (
    AccountPasswordCompliance,
    ApiRequestAuditEvent,
    ApiRiskAction,
    ApiRiskEvent,
    ApiRiskRule,
    PasswordPolicy,
)
from app.db.models.knowledge import (
    Chunk,
    Course,
    Document,
    DocumentAsset,
    KnowledgeEdge,
    KnowledgeNode,
)
from app.db.models.learning import (
    LearningEvent,
    LearningPath,
    LearningTask,
    QuizAttempt,
    QuizItem,
    QuizItemEvidence,
    QuizQualityReport,
)
from app.db.models.resource import GeneratedResource, ResourceVersion
from app.db.models.storage import StorageObject
from app.db.models.teaching import (
    Assessment,
    AssessmentAssignment,
    AssessmentGradeDecision,
    AssessmentItem,
    AssessmentSubmission,
    AssessmentVersion,
    ClassWeaknessSnapshot,
    CourseAssetGovernance,
    CourseDocumentBinding,
    CourseSyllabus,
    CourseSyllabusVersion,
    QuizReviewDecision,
    SyllabusExport,
    SyllabusReviewDecision,
    TeachingRecommendation,
    TeachingRecommendationDecision,
)
from app.db.models.workflow_runtime import (
    WorkflowApproval,
    WorkflowAuditLog,
    WorkflowCheckpoint,
    WorkflowEvidenceSnapshot,
    WorkflowEvent,
    WorkflowProviderCall,
    WorkflowRun,
    WorkflowStepAttempt,
)

KnowledgePoint = KnowledgeNode
KpPrerequisite = KnowledgeEdge

__all__ = [
    "Agent",
    "AgentMessage",
    "AgentRun",
    "AgentSkill",
    "AccountPasswordCompliance",
    "ApiRequestAuditEvent",
    "ApiRiskAction",
    "ApiRiskEvent",
    "ApiRiskRule",
    "BenchmarkCaseResult",
    "BenchmarkDatasetVersion",
    "BenchmarkRun",
    "CourseUpdateDecision",
    "CourseUpdateImpact",
    "CourseUpdateSuggestion",
    "Assessment",
    "AssessmentAssignment",
    "AssessmentGradeDecision",
    "AssessmentItem",
    "AssessmentSubmission",
    "AssessmentVersion",
    "Chunk",
    "ClassWeaknessSnapshot",
    "Course",
    "CourseEnrollment",
    "CourseAssetGovernance",
    "CourseDocumentBinding",
    "CourseSyllabus",
    "CourseSyllabusVersion",
    "CourseTeacherAssignment",
    "CourseResourceGovernance",
    "Document",
    "DocumentAsset",
    "GeneratedResource",
    "GovernanceAuditEvent",
    "ExternalSignal",
    "FairnessAlert",
    "FairnessAppeal",
    "FairnessConsent",
    "FairnessGroupAssignment",
    "FairnessMetricCell",
    "FairnessMetricRun",
    "FairnessPolicy",
    "FairnessReview",
    "KpiDefinition",
    "KnowledgeEdge",
    "KnowledgeNode",
    "KnowledgePoint",
    "KpPrerequisite",
    "LearningEvent",
    "LearningPath",
    "LearningTask",
    "Message",
    "MessageDelivery",
    "QuizAttempt",
    "QuizItem",
    "QuizItemEvidence",
    "QuizReviewDecision",
    "QuizQualityReport",
    "ResourceVersion",
    "RoleDefinition",
    "StudentGroup",
    "StudentGroupMember",
    "StorageObject",
    "SyllabusExport",
    "SyllabusReviewDecision",
    "TeachingClass",
    "TeachingClassTeacher",
    "TeachingRecommendation",
    "TeachingRecommendationDecision",
    "ProviderCredential",
    "PasswordPolicy",
    "User",
    "UserRoleGrant",
    "UserCapability",
    "UserProfile",
    "WorkflowCheckpoint",
    "WorkflowApproval",
    "WorkflowAuditLog",
    "WorkflowEvidenceSnapshot",
    "WorkflowEvent",
    "WorkflowProviderCall",
    "WorkflowRun",
    "WorkflowStepAttempt",
]
