import type { WebSecurityCurationMetadata, WebSecurityVideo } from '../types';

const videoMetadata: WebSecurityCurationMetadata = {
  source: 'external-preview',
  reviewer: 'SecureHub 课程内容组',
  reviewStatus: 'curated',
  sourceNote: '课程整理的 Bilibili 公开视频目录；本地静态保存公开页面声明的标题与封面，用于课程目录预览。',
  updatedAt: '2026-07-16T00:00:00Z',
  sourceTitle: 'WEBSEC-101 Bilibili 公开视频目录',
  licenseNote: '跳转 Bilibili 原平台观看。',
};

type CourseVideoInput = Pick<WebSecurityVideo, 'id' | 'title' | 'bvid' | 'url' | 'knowledgePointIds' | 'recommendedSegment' | 'learningGoal'>;

/**
 * Generated by frontend/scripts/fetch-websec-bilibili-covers.py from each
 * video's public page on 2026-07-16.  The assets are covers only: the app does
 * not download, play, transcode, or rehost Bilibili video content.
 */
const localCoverPathByBvid: Readonly<Record<string, string>> = {
  BV1PyARzDEHA: '/assets/websec/bilibili/BV1PyARzDEHA.jpg',
  BV1Zw4m1y7BX: '/assets/websec/bilibili/BV1Zw4m1y7BX.jpg',
  BV1FVMJ6yELZ: '/assets/websec/bilibili/BV1FVMJ6yELZ.jpg',
  BV1HJ4m1w7fB: '/assets/websec/bilibili/BV1HJ4m1w7fB.png',
  BV1HVMH6pE5h: '/assets/websec/bilibili/BV1HVMH6pE5h.jpg',
  BV17jN96fEhG: '/assets/websec/bilibili/BV17jN96fEhG.jpg',
};

function courseVideo(input: CourseVideoInput): WebSecurityVideo {
  const coverPath = input.bvid ? localCoverPathByBvid[input.bvid] : undefined;
  return {
    ...videoMetadata,
    ...input,
    fallbackUrl: 'https://www.bilibili.com/',
    cover: coverPath
      ? {
          url: coverPath,
          alt: `Bilibili 公开视频 ${input.bvid} 的原页面封面`,
        }
      : null,
    verification: {
      title: 'verified',
      author: 'pending',
      cover: coverPath ? 'verified' : 'unavailable',
      note: coverPath
        ? '标题与封面已从 Bilibili 公开视频页面静态采集；UP 主和内容以原平台页面为准。'
        : '标题已从公开视频页面静态采集；未缓存封面时保留 BVID 与原平台链接。',
    },
  };
}

export const webSecurityVideos: readonly WebSecurityVideo[] = [
  courseVideo({
    id: 'video-bv1pyarzdeha',
    title: '【网络安全入门系列】Web安全零基础入门到SRC挖洞实战！（Web安全入门/Web安全基础/Web安全实战/Web安全教程）',
    bvid: 'BV1PyARzDEHA',
    url: 'https://www.bilibili.com/video/BV1PyARzDEHA/',
    knowledgePointIds: ['http-basics', 'same-origin', 'cookie-session', 'owasp-top10'],
    recommendedSegment: '结合当前路线的 HTTP、浏览器边界和风险分类节点，优先记录视频中可验证的安全控制。',
    learningGoal: '建立 Web 通信边界、浏览器控制和常见风险类别之间的基础关联。',
  }),
  courseVideo({
    id: 'video-bv1zw4m1y7bx',
    title: '字节SRC总榜TOP1经验分享',
    bvid: 'BV1Zw4m1y7BX',
    url: 'https://www.bilibili.com/video/BV1Zw4m1y7BX/',
    knowledgePointIds: ['sql-injection', 'sql-injection-blind', 'secure-coding'],
    recommendedSegment: '围绕不可信输入、查询结构隔离和修复验证做笔记，并回到数据访问层审查任务练习。',
    learningGoal: '将参数化查询、最小权限和回归验证落实为可审查的数据库访问控制。',
  }),
  courseVideo({
    id: 'video-bv1fvmj6yelz',
    title: '【CTF夺旗赛】清华大学蓝莲花战队198小时内部培训CTF入门教程，零基础到进阶实战/CTF逆向/CTFweb/CTFpwn/CTFmisc',
    bvid: 'BV1FVMJ6yELZ',
    url: 'https://www.bilibili.com/video/BV1FVMJ6yELZ/',
    knowledgePointIds: ['xss-reflected', 'xss-stored', 'xss-dom', 'secure-coding'],
    recommendedSegment: '把内容与 HTML、属性、URL、DOM 等输出上下文分别对应，重点记录安全 API 与编码规则。',
    learningGoal: '区分 XSS 输出上下文，并选择模板转义与安全 DOM API 等主控制。',
  }),
  courseVideo({
    id: 'video-bv1hj4m1w7fb',
    title: '麻省理工学院 - MIT - 网络安全（我愿称之为网络安全教程天花板）',
    bvid: 'BV1HJ4m1w7fB',
    url: 'https://www.bilibili.com/video/BV1HJ4m1w7fB/',
    knowledgePointIds: ['csrf', 'cookie-session', 'auth-bypass'],
    recommendedSegment: '将状态变更请求、Cookie 属性、CSRF Token、Origin 校验和服务端授权分别记录为独立控制。',
    learningGoal: '避免将浏览器限制误作服务端授权，并建立状态变更接口的组合防护思路。',
  }),
  courseVideo({
    id: 'video-bv1hvmh6pe5h',
    title: '【网络安全入门合集】Web漏洞｜SQL注入｜XSS｜文件上传｜Kali信息收集｜漏洞扫描｜Linux加固｜等保测评',
    bvid: 'BV1HVMH6pE5h',
    url: 'https://www.bilibili.com/video/BV1HVMH6pE5h/',
    knowledgePointIds: ['file-upload', 'ssrf', 'deserialization', 'rce'],
    recommendedSegment: '从上传、出站请求和执行能力三个边界审视输入如何抵达高风险能力，并核对隔离和 allowlist。',
    learningGoal: '把服务端输入、出站请求和执行能力拆成可验证的安全边界。',
  }),
  courseVideo({
    id: 'video-bv17jn96fehg',
    title: '2026B站最新最详细的SQL注入漏洞攻防实战教程，全程干货无废话，手把手教你快速入门SQL注入/网络安全/web安全/渗透测试/漏洞挖掘',
    bvid: 'BV17jN96fEhG',
    url: 'https://www.bilibili.com/video/BV17jN96fEhG/',
    knowledgePointIds: ['auth-bypass', 'waf-bypass', 'secure-coding', 'owasp-top10'],
    recommendedSegment: '将认证、对象级授权、纵深防御、日志与回归验证拆开记录，避免把边界设备作为唯一修复。',
    learningGoal: '建立授权校验、纵深防御和修复闭环之间的边界意识。',
  }),
] as const;

export const webSecurityVideoById = Object.fromEntries(
  webSecurityVideos.map((video) => [video.id, video]),
) as Record<string, WebSecurityVideo>;
